openapi: 3.0.1
info:
  title: Simple-Finance API
  description: API de estudos Simple-Finance
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@arrudalabs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
#servers:
#  - url: https://simple-finance-backend.herokuapp.com/api
#  - url: http://simple-finance-backend.herokuapp.com/api

paths:
  /api/login:
    post:
      summary: Efetua Login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credenciais'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        default:
          description: Requisição inválida
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Erros'

components:
  schemas:
    Erros:
      type: object
      properties:
        mensagens:
          type: array
          items:
            type: string

    Credenciais:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password
    Token:
      type: object
      properties:
        token:
          type: string
          format: base64]
      required: [ token ]
