openapi: 3.0.1
info:
  title: Simple-Finance API
  description: API de estudos Simple-Finance
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@arrudalabs
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
#servers:
#  - url: https://simple-finance-backend.herokuapp.com/api
#  - url: http://simple-finance-backend.herokuapp.com/api

paths:
  /api/login:
    post:
      summary: Sign in
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        default:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

  /api/categories:
    get:
      description: Retrives a list of categories
      responses:
        200:
          description: Category List
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryList'
        default:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
    post:
      description: Add a new category
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewCategory'
      responses:
        201:
          description: Retrieves the created category
          headers:
            Location:
              description: the relative URL of the new category
              schema:
                type: string
                format: url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        default:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
  /api/categories/{id}:
    get:
      parameters: 
        - name: id
          description: Category ID
          in: path
          required: true
          schema:
            type: number
      responses:
        200:
          description: Retrieves the category by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        
components:
  schemas:
    NewCategory:
      type: object
      properties:
        type:
          type: string
          format: enum
          enum: ['CREDIT','DEBIT']
        description:
          type: string
      
    Category:
      type: object
      properties:
        id:
          type: number
        type:
          type: string
          format: enum
          enum: ['CREDIT','DEBIT']
        description:
          type: string
          
    CategoryList:
      type: array
      items:
        $ref: '#/components/schemas/Category' 
         
    Errors:
      type: object
      properties:
        mensagens:
          type: array
          items:
            type: string

    Credentials:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
      required:
        - email
        - password
    Token:
      type: object
      properties:
        token:
          type: string
          format: base64]
      required: [ token ]